name: Update Recent Activity

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update the Recent Activity section
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
